### PR TITLE
working setting saving and recalling

### PR DESCRIPTION
**Pull request by joshua255**
I tried to use the api functions but they weren't working.

### CODE REVIEW

**Comment by joshua255** [comment]
@jamdan2 @andrewda Let me know if you want to see the code I used on the DriverStation end. (it just requests settings until it gets them)

**Comment by andrewda** [comment]
@joshua255 yeah that'd be nice if you could post it here or Slack or smth

**Comment by joshua255** [comment]
```
void create() {//values to send
  addBoolean(enable);
  addByte(byte(speedVal));
  addByte(byte(turnSpeedVal));
  addByte(byte(0));//don't send aux vars
  addBoolean(advanced);
  addFloat(kP_angle);
  addFloat(kI_angle);
  addFloat(kD_angle);
  addFloat(kP_speed);
  addFloat(kI_speed);
  addFloat(kD_speed);
  if (recvdSettings==false) {//if flag for whether settings received is still false
    addByte(byte(1));//send a 1 asking for settings
    println("send");
  } else if (ss.t) {//if write settings button pushed
    ss.t=false;
    addByte(byte(2));//send a 2 telling the robot to write its settings to flash memory
    //the memory write takes time, and flash memory can only handle so many write cycles (100s of thousands, but writing every time around the loop could burn through that) so it is important to only ask for a write when necessary
    println("save");
  } else {
    addByte(byte(0));//don't send or write settings
    println("no");
  }
}
void parse() {
  isEnabled=parseBl();
  tipped=parseBl();
  ROBOT_ID=parseBy();
  MODEL_NO=parseBy();
  pitch=parseFl();
  voltage=int(parseBl());
  leftMotorSpeed=parseIn();
  rightMotorSpeed=parseIn();
  pitchTarget=parseFl();
  parseBy();//don't recieve auxVars
  if (parseBl()) {//if the robot signals that it will send its settings...
    kP_angle=parseFl();
    kI_angle=parseFl();
    kD_angle=parseFl();
    kP_speed=parseFl();
    kI_speed=parseFl();
    kD_speed=parseFl();
    recvdSettings=true;//read the settings and set a flag true
    println("recvd");
  }
}
```

**Comment by ghost** [comment]
@joshua255 try using the API functions again. I just realized that my code had the arguments backwards.

**Comment by joshua255** [comment]
@circuitbird I'll try the API functions again if you want me to, but what's the advantage? The functions I made are working. Is there a reference page for the API functions? Should the address for each writeFloat increment by 1 or by 4?

**Pull request merged**
